/*
    Compute shader used to update particles.
*/
#version 430

layout (local_size_x = 1, local_size_y = 1) in;

struct Particle {
    vec4 position;
    vec4 velocity;
};

layout(set = 0, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(set = 1, binding = 0) uniform UpdateBuffer {
    float deltaTime;
};

void main() {
    particles[gl_GlobalInvocationID.x].position += deltaTime * particles[gl_GlobalInvocationID.x].velocity;
}
